const texasResponses = [
  "Keeping Texas clean starts with picking up litter wherever you go",
  "Save water by turning off the tap when you brush your teeth",
  "Recycle plastic bottles to help reduce waste in Texas",
  "Plant native trees because they help our Texas wildlife thrive",
  "Use less electricity to reduce energy strain across Texas",
  "Switch to LED bulbs to save power in your Texas home",
  "Support Texas parks by visiting and respecting park rules",
  "Reuse shopping bags to keep Texas landfills from filling quickly",
  "Clean up after pets to protect Texas waterways",
  "Carpool with friends to reduce air pollution in Texas",
  "Use refillable water bottles to cut down on Texas plastic waste",
  "Turn off lights when not needed and help Texas conserve energy",
  "Keep Texas rivers clean by never dumping anything in storm drains",
  "Reduce food waste by planning meals and helping the Texas environment",
  "Support local Texas farmers by buying locally grown produce",
  "Pick up trash at beaches to protect Texas marine life",
  "Use public transport to ease traffic and emissions in Texas",
  "Recycle aluminum cans to save resources in Texas",
  "Keep Texas beautiful by disposing of batteries properly",
  "Compost food scraps to help Texas soil stay healthy",
  "Avoid overwatering plants to save Texas water",
  "Plant drought tolerant plants to support Texas landscapes",
  "Take shorter showers to conserve water in Texas homes",
  "Use a broom instead of a hose to clean driveways in Texas",
  "Turn off your car when waiting to reduce emissions in Texas",
  "Support Texas wildlife rescues and conservation groups",
  "Keep Texas roads clean by securing trash in your vehicle",
  "Use eco friendly cleaners to protect Texas air and water",
  "Help keep Texas lakes clean by minimizing chemical use",
  "Use a thermostat wisely to reduce energy in Texas summers",
  "Support Texas recycling programs in your community",
  "Avoid single use plastics to help Texas ecosystems",
  "Join a Texas community cleanup event to make an impact",
  "Protect Texas wildlife by keeping habitats undisturbed",
  "Use reusable straws to help reduce Texas plastic waste",
  "Keep Texas safe by reducing pollution from household chemicals",
  "Walk or bike when you can to reduce Texas carbon emissions",
  "Help Texas plants grow by avoiding overfertilizing lawns",
  "Recycle cardboard boxes to help Texas waste systems",
  "Turn off game consoles when not in use to save Texas power",
  "Support Texas forests by reducing paper waste",
  "Volunteer at Texas nature centers to give back",
  "Keep Texas water clean by fixing leaks quickly",
  "Use fans instead of AC when possible to save Texas energy",
  "Teach others how to help keep Texas clean and safe",
  "Support Texas renewable energy when possible",
  "Bring reusable containers to reduce waste in Texas",
  "Keep Texas playgrounds safe by picking up trash",
  "Choose products with less packaging for Texas waste reduction",
  "Keep Texas skies clear by reducing burning of waste",
  "Participate in Texas river cleanups to protect ecosystems",
  "Make sure your car tires are filled to save Texas fuel",
  "Recycle glass bottles to help Texas recycling efforts",
  "Reuse old items instead of tossing them to help Texas",
  "Support Texas wildlife by leaving water out in hot weather",
  "Learn about Texas environment issues and help spread awareness",
  "Keep Texas hiking trails clean by packing out trash",
  "Choose Texas friendly landscaping to support local climates",
  "Help Texas bees by planting flowering plants",
  "Reduce noise pollution to help Texas wildlife stay calm",
  "Purchase secondhand items to reduce Texas landfill waste",
  "Support Texas water conservation events",
  "Eat more plant based meals to lower Texas resource use",
  "Limit idling to reduce Texas air pollution",
  "Recycle old clothes to support Texas textile programs",
  "Use natural light to lower Texas electricity use",
  "Collect rainwater when possible to save Texas water",
  "Donate unused items to reduce Texas waste",
  "Avoid harmful pesticides to help Texas insects and birds",
  "Stay on trails to protect Texas plant life",
  "Adopt pets from Texas shelters instead of breeders",
  "Unplug chargers to reduce Texas phantom energy use",
  "Keep Texas storm drains clear by disposing waste properly",
  "Support Texas environmental education programs",
  "Grow a home garden to help Texas food sustainability",
  "Avoid balloon releases to protect Texas animals",
  "Take care of Texas by recycling electronics responsibly",
  "Use bike lanes to reduce emissions in Texas cities",
  "Take reusable bags to Texas stores to reduce waste",
  "Help clean graffiti to beautify Texas communities",
  "Support Texas composting programs",
  "Repair items instead of replacing them to help Texas resources",
  "Turn off sprinklers when it rains to save Texas water",
  "Protect Texas birds by keeping windows visible",
  "Use low flow faucets to save Texas water",
  "Help Texas turtles by keeping beaches clean",
  "Buy local fish to support Texas fisheries",
  "Avoid throwing plastic in Texas waterways",
  "Reduce printing to save Texas trees",
  "Keep Texas parks quiet to support wildlife",
  "Make Texas greener by planting shrubs and trees",
  "Clean up local Texas streets with friends",
  "Support Texas recycling laws and programs",
  "Practice responsible fishing in Texas waters",
  "Pick up litter at school to help Texas",
  "Store food properly to reduce Texas waste",
  "Carry a trash bag in your car to help Texas stay clean"
];


// Suggested follow ups
var texasSuggestions = [
  "What else can Texans do to help the environment",
  "Want to hear another way to protect Texas nature",
  "Would you like another Texas conservation tip",
  "Do you want to learn another Texas friendly habit",
  "Ready for another idea to help keep Texas clean",
  "Want another simple way to care for Texas",
  "Want a suggestion to keep Texas beautiful",
  "Want another helpful Texas habit"
];
